name: CI

on:
  push:
    branches: [master]
  pull_request:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  check:
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
          targets: ${{ matrix.target }}
      - uses: Swatinem/rust-cache@v2
      - run: cargo clippy --target ${{ matrix.target }} -- -D warnings
      - run: cargo test --target ${{ matrix.target }} --no-fail-fast
